### ISSUE TITLE
Windows 10 - $Error: Command failed: The system cannot find the path specified.\r

### ISSUE THREAD

**Issue by R9anSmart** [AnthonyGress/FireTV-Toolkit#1]
## Expected Behavior

The connection should be successful/a a prompt come up on the fireTV stick to allow debugging from the connection

## Current Behavior

$Error: Command failed: %appdata%\\Android-Toolkit\\platform-tools\\adb connect 192.168.0.107
The system cannot find the path specified.\r

![image](https://github.com/AnthonyGress/Android-Toolkit/assets/100030137/646b44a3-df02-437d-860d-20a1092c73b3)

## Steps to Reproduce

1. Scan the IP range for the FireTV stick

2.Fails

## Context

Unable to connect to FireTV stick to test pushing .APKS and the tools that are built in

## Your Environment

-   Node version : ???
-   App version : 1.3.8
-   Operating System and version : Windows 10 Pro
-   Link to your project : Na

**Comment by AnthonyGress** [comment]
Thanks for pointing this out. The picture was very helpful, I should have a fix pushed up for you soon.

**Comment by AnthonyGress** [comment]
@R9anSmart This issue should be resolved now with the latest version. I will reopen this if you continue to have an issue, let me know. I've also updated the readme with some helpful instructions on using it the first time. 

Download link to latest version: [https://github.com/AnthonyGress/Android-Toolkit/releases/latest](https://github.com/AnthonyGress/Android-Toolkit/releases/latest)

**Comment by R9anSmart** [comment]
Connected up with Windows now thanks.
Having issues with opening the shell to the device now but will open another issue :)

**Comment by AnthonyGress** [comment]
> Connected up with Windows now thanks.
> 
> Having issues with opening the shell to the device now but will open another issue :)

Yeah the shell is only on mac/Linux right now. I can add that too in the future. Thanks for the suggestions!
