### ISSUE TITLE
Software auto-update/update button

### ISSUE THREAD

**Issue by R9anSmart** [AnthonyGress/FireTV-Toolkit#19]
Hi,
A auto update feature or a update link to the GitHub page etc in the help menu would be awesome :)

**Comment by AnthonyGress** [comment]
This feature is already available. It was added a few days ago in version 1.5.7. You should get notified when new updates are available. Try downloading version 1.5.11 and it should notify you of the update below the title @R9anSmart 

<img width="1019" src="https://github.com/AnthonyGress/Android-Toolkit/assets/70029654/df6423de-72fb-4973-aa5b-b40253cc94a9">

**Comment by R9anSmart** [comment]
Is there no easy link to the Github page etc that can be added to the windows version or something so I dont need to bookmark the page each time?

**Comment by AnthonyGress** [comment]
> Is there no easy link to the Github page etc that can be added to the windows version or something so I dont need to bookmark the page each time?

You should be able to update from within the app when a new update is available. That said, the buttons in the help menu link to the github. I can add another button for releases in the future
