### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by imaoreo** [AnthonyGress/FireTV-Toolkit#29]
## Prerequisites
- Windows 10

## Expected Behavior
- For the app to install fully

## Current Behavior
- I installed the app on the newest version and it always just makes a Uninstall file here 
![image](https://github.com/AnthonyGress/Android-Toolkit/assets/160131709/db2951d1-dbec-4b79-b63f-0201a4de514f)
and the shortcut that it makes leads to no where
- I then installed a previous version of the app which downloaded and opened using the shortcut but it never downloaded any adb stuff and when I manually put it in it still couldn't use it
- I then tried to update the old version which then it kept trying to access a folder that didn't exist

## Steps to Reproduce

- Explained in the Current Behavior

## Possible Solution (Not obligatory)

- I feel like the problem is to do with me changing my main user account from 44752 to Jay since in the file system it is still under 44752.

## Context

I was trying to install the app

## Your Environment

-   App version : Newest 
-   Device (Phone, FireTV, AndroidTV) and Android version : Fire Stick FireOS 9

**Comment by AnthonyGress** [comment]
@kezza2k7 The app does use the username of the user who installed it in the path for installing resources. What do you mean you changed your main user account but the filesystem is under another account? You can try to create a new user and install the app and see if the issue still persists.

**Comment by AnthonyGress** [comment]
Closing this issue as it seems to be a user error and there was no additional response.
