### ISSUE TITLE
Automated tools - LauncherHijack

### ISSUE THREAD

**Issue by R9anSmart** [AnthonyGress/FireTV-Toolkit#3]
Would be great if you could link a automated button for some of the other GitHub projects out there such as [LauncherHijack](https://github.com/BaronKiko/LauncherHijack)

**Comment by AnthonyGress** [comment]
@R9anSmart What device are you wanting to remap launcher? FireStick?

**Comment by R9anSmart** [comment]
Yes Firestick.
I have a few of them and would like to try to gain a more stock android experence

**Comment by AnthonyGress** [comment]
I use launcher manager and wolf launcher. Not sure if it works on newer versions of fireOS. I do know of some other remappers that work and are still supported. I can add buttons to easily install those if we confirm they work. There is also the project ivy launcher which I also like.

**Comment by R9anSmart** [comment]
Something like that would be amazing! I am finding it hard to find anything currently supported after using FireStarter back in the day which I dont think works now.

Thanks again :)

**Comment by AnthonyGress** [comment]
@R9anSmart This feature has been implemented, try installing launcher manager and see if that does what you want.
