### ISSUE TITLE
Request - Batch install/sideload .apks

### ISSUE THREAD

**Issue by R9anSmart** [AnthonyGress/FireTV-Toolkit#6]
Would be great if we could select more that one .apk and sideload them in a que :)

**Comment by AnthonyGress** [comment]
Good idea, this will be easy enough to implement

**Comment by AnthonyGress** [comment]
This feature has been added. Note, on linux/windows when you select a folder to batch install, it is currently not possible to show the existing files inside the folder. Just select the folder that contains your APK's and it will install them all.
